### PR TITLE
Added NanoPi R5S support

### PR DESCRIPTION
**Pull request by buglloc**
Should work for both [FriendlyElec Nanopi R5S](https://www.friendlyelec.com/index.php?route=product/product&product_id=287) and [FriendlyElec Nanopi R5C](https://www.friendlyelec.com/index.php?route=product/product&product_id=290), but I doesn't have R5C yet to test.

Device tree built from linux 6.1.18. Source code: https://github.com/buglloc/nanopi-r5/tree/main/dtb
u-boot - signed with rockchip binaries: https://github.com/friendlyarm/rkbin/tree/nanopi5 && https://github.com/buglloc/nanopi-r5/tree/main/uboot

### CODE REVIEW

**Comment by ophub** [comment]
谢谢分享，我打包下，你随后测试下。

**Comment by altmangood** [comment]
刷了 Armbian_23.05.0_rockchip_nanopi-r5s_bullseye_6.1.26_server_2023.04.27 基本功能使用正常。

2个问题：
1、2 个 2.5G LAN Port,  网络灯不亮，但是能正常分IP 访问外网。
2、USB WiFi 没法识别，我那个USBWiFi在其他板子的固件5.15.x 和 6.1.x 的内核都能直接识别

**Comment by kongjun0** [comment]
You can refer to  https://github.com/inindev/nanopi-r5  differentiate between R5S and R5C，I have tested it on R5C。In addition, the nanopi official RTC time should point to RTC1. Hope to modify the kernel compilation code in the next version.Web page source：https://wiki.friendlyelec.com/wiki/index.php/RTC    

  Build the RTC driver into the kernel (not an external module)
Go to the following location:

  │   Location:                                                                                                                  │
  │     -> Device Drivers                                                                                                        │
  │       -> Real Time Clock (RTC_CLASS [=y])                                                                                    │
Set CONFIG_RTC_DRV_DS1307 to 'y'.

3.2 Specify the correct RTC device
Since the default kernel rtc device is rtc0, and when we use external rtc in Allwinner platform, the external rtc is usually initialized to rtc1, so we also need to modify the following kernel configuration to set the value to rtc1:

CONFIG_RTC_HCTOSYS_DEVICE="rtc1"
CONFIG_RTC_SYSTOHC_DEVICE="rtc1"
The kernel configuration:

diff --git a/arch/arm/configs/sunxi_defconfig b/arch/arm/configs/sunxi_defconfig
index 4c88bbb8..4dbee1a9 100644
--- a/arch/arm/configs/sunxi_defconfig
+++ b/arch/arm/configs/sunxi_defconfig
@@ -1027,11 +1027,12 @@ CONFIG_LEDS_TRIGGER_DEFAULT_ON=y
 CONFIG_LEDS_TRIGGER_PANIC=y
 CONFIG_LEDS_TRIGGER_NETDEV=y
 CONFIG_RTC_CLASS=y
+CONFIG_RTC_HCTOSYS_DEVICE="rtc1"
 CONFIG_RTC_INTF_DEV_UIE_EMUL=y
 CONFIG_RTC_DRV_TEST=m
 CONFIG_RTC_DRV_ABB5ZES3=m
 CONFIG_RTC_DRV_ABX80X=m
-CONFIG_RTC_DRV_DS1307=m
+CONFIG_RTC_DRV_DS1307=y
 CONFIG_RTC_DRV_DS1307_CENTURY=y
 CONFIG_RTC_DRV_DS1374=m
 CONFIG_RTC_DRV_DS1374_WDT=y

I have R5C device to test

**Comment by kongjun0** [comment]
image

**Comment by ophub** [comment]
@kongjun0 

Thank you for your sharing. Based on the support you provided at https://github.com/inindev/nanopi-r5, I have utilized the precompiled u-boot and dtb files. I've packaged the firmware for the R5C. Please download and test it to confirm its functionality.

https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_bullseye_save_2023.08/Armbian_23.08.0_rockchip_nanopi-r5c_bullseye_6.1.46_server_2023.08.17.img.gz

**Comment by kongjun0** [comment]
R5C has been roughly tested, and no functional problems have been found, and the LED lights of the two network ports are not on. Data sending and receiving is normal, please refer to https://github.com/indev/nanopi-r5/blob/main/dtb/patches/0001-add-led-triggers.patch to see if it can be repaired.

**Comment by ophub** [comment]
I am using his versions, both the u-boot and dtb are from him, and he has applied these patches. The files are from his latest compilation four days ago:

https://github.com/inindev/nanopi-r5/releases/tag/v12.0.2

**Comment by kongjun0** [comment]
看这个能否解决网络led灯亮问题，
Config status LEDs
First determine whether the system already exists the leds initialization service:

sudosystemctl status leds
If the leds service already exists, change the default behavior of the LEDs by editing the following file:

/etc/init.d/leds.sh
Since there is no leds service in the early firmware, you need to refer to the following guide to manually configure the LEDs. First, set the following kernel modules to be automatically loaded at boot:
modprobe ledtrig-netdevecho ledtrig-netdev > /etc/modules-load.d/ledtrig-netdev.conf
Put the following into the autorun script to associate the status leds with the ethernet interface, and you can configure it to behave in other ways by referring to these content:
echonetdev> /sys/class/leds/wan_led/triggerecho eth0 > /sys/class/leds/wan_led/device_name
echo 1 > /sys/class/leds/wan_led/link
 
echonetdev> /sys/class/leds/lan_led/triggerecho eth1 > /sys/class/leds/lan_led/device_name
echo 1 > /sys/class/leds/lan_led/link

**Comment by ophub** [comment]
你手动执行试试

**Comment by kongjun0** [comment]
手动执行不成功在ARMBIAN上   。
我觉得在armbian上没有成功或许有2点，第一网口定义不同导致没有成功
image
第二,DTB有一个新增补丁可能在编译过程后添加，只提取DTB文件导致这个新增不包含在内，不知理解有没有错误？我不太懂编译，希望对你的编译过程产生思路。
image
我在能正常显示指示灯的固件截图和armbian对比多几个文件
QQ截图20230820085004

**Comment by ophub** [comment]
我直接使用的他编好的，我觉的他巳经使用了这个补丁。要不你问一下作者还有什么地方漏了其他设置。

**Comment by kongjun0** [comment]
> 我直接使用的他编好的，我觉的他巳经使用了这个补丁。要不你问一下作者还有什么地方漏了其他设置。

有没有可能是网络定义名称不一样导致不能正常工作，他定义的是lan0   wan0   你使用的是eth0  eth1    你可以也定义成lan0   wan0  试一下，我来测试，官方固件也是用lan0  和lan1定义

**Comment by kongjun0** [comment]
作用说看下这个能否解决？有人也同样这个问题。https://github.com/inindev/nanopi-r5/issues/19

**Comment by kongjun0** [comment]
Screenshot_2023-08-21-20-11-40-746_com android chrome
Screenshot_2023-08-21-20-22-28-013_com android chrome
Screenshot_2023-08-21-20-24-49-251_com android chrome

**Comment by kongjun0** [comment]
Screenshot_2023-08-21-20-23-31-972_com android chrome

**Comment by kongjun0** [comment]
较新版本的 u-boot（高于 12.0.0 版本）不会在启动分区的目录中查找 DTB 文件，作者提示可以用v12.0.3版本试试？下个版本可否试下
image

**Comment by ophub** [comment]
12.0.3不是比12.0.0更新？

**Comment by kongjun0** [comment]
12.0.3吧！
Screenshot_2023-08-27-20-48-36-600_com android chrome

**Comment by kongjun0** [comment]
意思就是没调用dtb文件，看有别的方法让调用不，上面截图是r5s人家是uefi启动,修改配置后解决

**Comment by ophub** [comment]
r5s 和 r5c 的 U-BOOT 和 DTB 我都更新了，jammy的2个正在编译，你一会10分钟后到jammy里下载试试。

**Comment by kongjun0** [comment]
已经刷机还是不显示，能否通过修改启动引导DTB让加载DTB文件？有没有方法？

**Comment by ophub** [comment]
如果没有加载dtb是无法使用的。

比如你把现在的dtb删了，拿个别的dtb改名成它的名字，肯定启动不了，各种报错网卡找不到之类的错误。

**Comment by kongjun0** [comment]
> 如果没有加载dtb是无法使用的。
> 
> 比如你把现在的dtb删了，拿个别的dtb改名成它的名字，肯定启动不了，各种报错网卡找不到之类的错误。
> 
> 网络正常就可以了，网卡灯不亮就不亮吧

好吧

**Comment by maojianyou** [comment]
> 谢谢分享，我压缩下，你再测试下。


友善R5C刷机步骤，电脑通过USB3.0--USB3.0公转公刷机到emmc，32G，没有SD卡
1、下载bin引导文件
https://github.com/ophub/u-boot/blob/main/u-boot/rockchip/nanopi-r5s/rk3568_ddr_1560MHz_v1.15.bin

2、下载R5C部分引导文件
https://github.com/ophub/u-boot/blob/main/u-boot/rockchip/nanopi-r5c/idbloader.img

https://github.com/ophub/u-boot/blob/main/u-boot/rockchip/nanopi-r5c/u-boot.itb

3、下载img镜像
https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_bookworm_save_2024.04/Armbian_24.5.0_rockchip_nanopi-r5c_bookworm_6.1.84_server_2024.04.08.img.gz


上面下载好后
然后下载驱动跟刻录软件
https://github.com/ophub/kernel/releases/download/tools/Radxa_rock5b_RKDevTool_Release_v2.96__DriverAssitant_v5.1.1.tar.gz

然后把上面工具机系统放入到一个目录下
具体上面如何使用，貌似不行，刷机失败
image

能否提供一个详细的友善R5C刷机教程

**Pull request merged**
