### PR TITLE
Add Bluetooth support for X96 Max+ Q2 and X96 Air Q1000 to model database

### PR DESCRIPTION
**Pull request by danboid**
…base

### CODE REVIEW

**Comment by danboid** [comment]
Bluetooth is working fine on both models but there is an issue with wifi I need to look into.

Wifi mostly works but I get the error:

ath10k_sdio mmc0:0001:1: DFS region 0x0 not supported, will trigger radar for every pulse

Frequently printed to the console. I can't ssh in via the wifi IP whilst I can ssh into it fine via its ethernet address.

**Comment by danboid** [comment]
I've made a few updates to TVBIRR over the last few days. It now supports text-to-speech so it can speak the name of the track or station you are listening to and I've written a guide on how to also make it work as a Bluetooth speaker.

https://github.com/danboid/TVBIRR

**Comment by ophub** [comment]
I just read the description of your TVBIRR, this is really a valuable development project, have you made some simple operation instructions for him? E.g 
```
armbian-tvbirr play
armbian-tvbirr next
armbian-tvbirr stop
```

After reading your project, I suddenly seem to be doing a software center, such as armbian-software, to install and use some interesting projects like yours with one click.

There is a concise development instruction document, which supports independent use of each project, and also supports installation and use in the software center.

**Comment by danboid** [comment]
I'm happy you are interested in my project but it looks like you misunderstood text-to-speech.

TVBIRR doesn't currently have any support for microphones and control by voice. All it can do is speak and tell you what track is currently playing or the address of the current station being streamed.

I have updated the README just now to make it a bit clearer about this and a few other details.

**Pull request merged**
